pdf-engine: xelatex

input-file: index.md
output-file: index.pdf

metadata:
  title:  "eBook template"
  subtitle: "Version: 1.0"
  author:
    - Denis Borovensky

toc: true
toc-depth: 4
number-sections: true
top-level-division: part

highlight-style: zenburn

variables:
  mainfont: Rubik
  documentclass: report
  toc-title: "Содержание"
  colorlinks: true
  urlcolor: NavyBlue
  toccolor: black